name: Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'        
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64' 
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Download QtMsBuild Targets
      run: git clone https://code.qt.io/qt-labs/vstools.git

    - name: Build the solution
      env:
        QtMsBuild: ${{ github.workspace }}\vstools\QtMsBuild
      run: |
        msbuild QSimplePOS.sln /p:Configuration=Release /p:Platform=x64
      shell: pwsh
      
    - name: Run Unit Tests
      run: .\x64\Release\QSimplePOSTEST.exe
     
